---
- hosts: all
  gather_facts: false
  remote_user: root

  vars:
    mirror: "https://fastly.cdn.openbsd.org/pub/OpenBSD"
    release: '6.2'
#   https://www.openbsd.org/anoncvs.html
    cvs: 'anoncvs@mirror.osn.de:/cvs'
    github_user: "alexlovelltroy"
    pkg_path: "{{ mirror }}/{{ release }}/packages/amd64/"

  tasks:
  - name: add a new user
    user: name=alt comment="Alex Lovell-Troy" groups=wheel,wsrc append=yes
    become_method: sudo
    become: true

  - name: ensure root SSH keys are installed
    authorized_key: user=root key=https://github.com/{{ github_user }}.keys
    become_method: sudo
    become: true

  - name: ensure user SSH keys are installed
    authorized_key: user=alt key=https://github.com/{{ github_user }}.keys
    become_method: sudo
    become: true

  - name: /etc/doas.conf
    blockinfile:
      dest: /etc/doas.conf
      create: yes
      block: |
        permit nopass keepenv setenv { ENV PS1 SSH_AUTH_SOCK } :wheel
        permit nopass keepenv setenv { ENV PS1 SSH_AUTH_SOCK } :wsrc
    become_method: sudo
    become: true
  
  - name: setup package mirror
    blockinfile:
      dest: /etc/installurl
      create: yes
      block: |
        {{ mirror }}
    become_method: sudo
    become: true

  - name: install packages
    openbsd_pkg: name={{ item }} state=present
    with_items:
        - git
        - gmake
        - mc
        - vim--no_x11
        - py-pip
        - openvpn
        - screen-4.0.3p6
        - go
        - go-tools
        - zsh
        - mutt-1.9.1v3
        - gnupg-1.4.21p2

    become_method: sudo
    become: true    

  - name: .gitconfig
    blockinfile:
      dest: /home/alt/.gitconfig
      create: yes
      owner: alt
      block: |
        [user]
                name = Alex Lovell-Troy
                email = alex@lovelltroy.org

        [push]
                default = simple

        [color]
                ui = true
    become_method: sudo
    become: true


  - name: checkout Jess's dotfiles dotfiles
    git:
      repo: https://github.com/jessfraz/dotfiles.git
      dest: "/home/alt/dotfiles"
      track_submodules: yes
      recursive: yes
      clone: yes
      update: yes
    become_method: doas
    become: true

  - name: .extra
    blockinfile:
      dest: /home/alt/.extra
      create: yes
      owner: alt
      block: |
        ###
        ### Git credentials
        ###

        GIT_AUTHOR_NAME="Alex Lovell-Troy"
        GIT_COMMITTER_NAME="$GIT_AUTHOR_NAME"
        git config --global user.name "$GIT_AUTHOR_NAME"
        GIT_AUTHOR_EMAIL="alex@lovelltroy.org"
        GIT_COMMITTER_EMAIL="$GIT_AUTHOR_EMAIL"
        git config --global user.email "$GIT_AUTHOR_EMAIL"
        GH_USER="nickname"
        git config --global github.user "$GH_USER"

        ###
        ### Gmail credentials for mutt
        ###
        export GMAIL=alex.lovelltroy@gmail.com
        export GMAIL_NAME="Alex Lovell-Troy"
        export GMAIL_FROM=alex@lovelltroy.org
    become_method: sudo
    become: true


  - name: checkout Jess's vim config
    git:
      repo: https://github.com/jessfraz/.vim.git
      dest: "/home/alt/.vim"
      track_submodules: yes
      recursive: yes
      clone: yes
      update: yes
      force: yes
    become_method: doas
    become: true

      
  - name: Update .vimrc
    file:
      src: /home/alt/.vim/vimrc
      dest: /home/alt/.vimrc
      owner: alt
      group: alt
      state: link
    become_method: sudo
    become_user: alt
    become: true


  - name: /etc/installurl
    lineinfile:
      dest=/etc/pkg.conf
      backup=yes
      line="{{ pkg_path }}"
      state=present
      create=True
    become_method: sudo
    become: true



  - name: create a directory
    file: path=/home/alt/{{ release }} state=directory
    become_user: alt


  - name: download release sources ports.tar.gz
    get_url:
       url: "{{ mirror }}/{{ release }}/{{ item.component }}.tar.gz"
       dest: /home/alt/{{ release }}/
       mode: 0440
       sha256sum: "{{ item.cksum }}"
    with_items:
      - { component: 'ports', cksum: '79c6fc497cfa23504e9cf5734b5c70b509b3caa433c5ecc316a8788001e52255' }
    become_user: alt


  - name: checkout OpenBSD sources (ports)
    git:
      repo: https://github.com/openbsd/{{ item.component }}
      dest: "{{ item.path }}"
      accept_hostkey: yes
      clone: yes
      update: yes
    with_items:
      #- { component: 'src', path: '/usr/src' }
      - { component: 'ports', path: '/usr/ports' }

  - name: make 'wsrc' owner of ports
    file:
      path: /usr/ports
      mode: u=rwX,g=rwX,o=rX
      group: wsrc
      recurse: yes
    become_method: su
    become: true

  # signify -Gns /etc/signify/my-pkg.sec -p /etc/signify/my-pkg.pub
  # cd /usr/ports/packages/$(uname -p)
  # pkg_sign -s signify -s /etc/signify/my-pkg.sec -o signed -S all

  - name: add PORTSDIR_PATH and SIGNING_PARAMETERS to /etc/mk.conf
    blockinfile:
      dest: /etc/mk.conf
      content: |
        PORTSDIR_PATH=${PORTSDIR}:$(PORTSDIR)/openbsd-wip:${PORTSDIR}/mystuff
        SIGNING_PARAMETERS=-s signify -s /etc/signify/my-pkg.sec 
      backup: yes
      state: present
      create: True

#  - name: checkout OpenBSD sources from CVS
#    command: CVSROOT={{ cvs }}; cd /usr/ && cvs -d {{ item }} -q up -Pd
#    with_items:
#        - src
#        - sys
#        - xenocara
#        - www
